# Generated by Django 5.0.6 on 2024-05-26 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=2, max_digits=7)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=7)),
                ('name', models.CharField()),
                ('region', models.CharField(blank=True, default='')),
                ('country', models.CharField()),
                ('tz_id', models.CharField()),
                ('localtime_epoch', models.IntegerField()),
                ('localtime', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField()),
                ('last_updated_epoch', models.IntegerField()),
                ('temp_c', models.DecimalField(decimal_places=2, max_digits=7)),
                ('temp_f', models.DecimalField(decimal_places=2, max_digits=7)),
                ('feelslike_c', models.DecimalField(decimal_places=2, max_digits=7)),
                ('feelslike_f', models.DecimalField(decimal_places=2, max_digits=7)),
                ('condition', models.JSONField()),
                ('wind_mph', models.DecimalField(decimal_places=2, max_digits=7)),
                ('wind_kph', models.DecimalField(decimal_places=2, max_digits=7)),
                ('wind_degree', models.IntegerField()),
                ('wind_dir', models.CharField()),
                ('pressure_mb', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pressure_in', models.DecimalField(decimal_places=2, max_digits=7)),
                ('precip_mm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('precip_in', models.DecimalField(decimal_places=2, max_digits=7)),
                ('humidity', models.IntegerField()),
                ('cloud', models.IntegerField()),
                ('is_day', models.IntegerField()),
                ('uv', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gust_mph', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gust_kph', models.DecimalField(decimal_places=2, max_digits=7)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
    ]
